extends Node

const DAMAGE_INCREMENT: int = 5
const REGEN_INCREMENT: int = 1
const SPEED_INCREMENT: int = 25
const KNOCKBACK_INCREMENT: int = 1
const FIRERATE_INCREMENT: float = 0.05
const MAX_HEALTH_INCREMENT: int = 10
const BULLET_SIZE_INCREMENT: float = 0.25
const BULLET_SPEED_INCREMENT: int = 50
const PIERCE_INCREMENT: int = 1
