extends Node

const DAMAGE_INCREMENT: int = 3
const REGEN_INCREMENT: int = 3
const SPEED_INCREMENT: int = 20
const KNOCKBACK_INCREMENT: int = 75
const FIRERATE_INCREMENT: float = 0.15
const MAX_HEALTH_INCREMENT: int = 15
const BULLET_SIZE_INCREMENT: float = 0.6
const BULLET_SPEED_INCREMENT: int = 50
const PIERCE_INCREMENT: int = 1
