extends Node

const MIN_SPAWN_TIME = 1

const BASIC_SHOOTER_HEALTH = 30
const BASIC_SHOOTER_DAMAGE = 10
const BASIC_SHOOTER_SPEED = 100
const BASIC_SHOOTER_PROJECTILE_SPEED = 300
const BASIC_SHOOTER_FIRERATE_COOLDOWN = 1.5
const BASIC_SHOOTER_BULLET_SCALE = 0.65
const BASIC_SHOOTER_MIN_DISTANCE_THRESHOLD = 200
const BASIC_SHOOTER_MAX_DISTANCE_THRESHOLD = 500
const BASIC_SHOOTER_ENEMY_NAME = "Basic Shooter"
const BASIC_SHOOTER_GOLD_DROP_RANGE = 15
const BASIC_SHOOTER_XP_DROP_RANGE = 50
const BASIC_SHOOTER_GOLD_DROP_CHANCE = 0.5
const BASIC_SHOOTER_GOLD_DROP_COUNT = 1
const BASIC_SHOOTER_XP_DROP_COUNT = 5
const BASIC_SHOOTER_ITEM_DROP_CHANCE = 1
const BASIC_SHOOTER_ITEM_DROP_COUNT = 0.001
const BASIC_SHOOTER_MIN_SPAWN_DIST = 650
const BASIC_SHOOTER_SPAWN_RADIUS = 850

const WEAK_RUSHER_HEALTH = 10
const WEAK_RUSHER_DAMAGE = 5
const WEAK_RUSHER_MIN_SPEED = 75
const WEAK_RUSHER_MAX_SPEED = 100
const WEAK_RUSHER_ENEMY_NAME = "Weak Rusher"
const WEAK_RUSHER_GOLD_DROP_RANGE = 25
const WEAK_RUSHER_XP_DROP_RANGE = 25
const WEAK_RUSHER_GOLD_DROP_COUNT = 1
const WEAK_RUSHER_XP_DROP_COUNT = 2
const WEAK_RUSHER_GOLD_DROP_CHANCE = 0.2
const WEAK_RUSHER_MIN_SPAWN_AMOUNT = 1
const WEAK_RUSHER_MAX_SPAWN_AMOUNT = 2
const WEAK_RUSHER_MIN_SPAWN_DIST = 750
const WEAK_RUSHER_SPAWN_RADIUS = 1000

const SNIPER_HEALTH = 50
const SNIPER_DAMAGE = 25
const SNIPER_SPEED = 150
const SNIPER_PROJECTILE_SPEED = 800
const SNIPER_FIRERATE_COOLDOWN = 3
const SNIPER_BULLET_SIZE = 0.8
const SNIPER_ENEMY_NAME = "Sniper"
const SNIPER_MIN_DISTANCE_THRESHOLD = 500
const SNIPER_MAX_DISTANCE_THRESHOLD = 800
const SNIPER_GOLD_DROP_RANGE = 30
const SNIPER_XP_DROP_RANGE = 50
const SNIPER_GOLD_DROP_COUNT = 1
const SNIPER_XP_DROP_COUNT = 8
const SNIPER_ITEM_DROP_CHANCE = 0.01
const SNIPER_ITEM_DROP_COUNT = 1
const SNIPER_MIN_SPAWN_DIST = 1000
const SNIPER_SPAWN_RADIUS = 1500

const TANKY_ENEMY_NAME = "Tanky"
const TANKY_SPEED = 50
const TANKY_DAMAGE = 15
const TANKY_HEALTH = 125
const TANKY_GOLD_DROP_RANGE = 30
const TANKY_XP_DROP_RANGE = 50
const TANKY_GOLD_DROP_COUNT = 1
const TANKY_XP_DROP_COUNT = 8
const TANKY_ITEM_DROP_CHANCE = 0.01
const TANKY_ITEM_DROP_COUNT = 1
const TANKY_MIN_SPAWN_DIST = 850
const TANKY_SPAWN_RADIUS = 1250

const SHOTGUNNER_ENEMY_NAME = "Shotgunner"
const SHOTGUNNER_SPEED = 100
const SHOTGUNNER_FIRERATE_COOLDOWN = 2
const SHOTGUNNER_PROJECTILE_SPEED = 450
const SHOTGUNNER_DAMAGE = 15
const SHOTGUNNER_BULLET_SIZE = 0.8
const SHOTGUNNER_HEALTH = 100
const SHOTGUNNER_MIN_DISTANCE_THRESHOLD = 500
const SHOTGUNNER_MAX_DISTANCE_THRESHOLD = 800
const SHOTGUNNER_GOLD_DROP_RANGE = 30
const SHOTGUNNER_XP_DROP_RANGE = 50
const SHOTGUNNER_GOLD_DROP_COUNT = 2
const SHOTGUNNER_XP_DROP_COUNT = 5
const SHOTGUNNER_ITEM_DROP_CHANCE = 0.01
const SHOTGUNNER_ITEM_DROP_COUNT = 1
const SHOTGUNNER_MIN_SPAWN_DIST = 850
const SHOTGUNNER_SPAWN_RADIUS = 1250
const SHOTGUNNER_SHOT_AMOUNT = 3

const SHOTGUNNER_LIMIT: int = 5
const SNIPER_LIMIT: int = 2
const TANKY_LIMIT: int = 2
const BASIC_SHOOTER_LIMIT: int = 5

const ENEMY_LIMITS = {
	TANKY_ENEMY_NAME: TANKY_LIMIT,
	SNIPER_ENEMY_NAME: SNIPER_LIMIT,
	BASIC_SHOOTER_ENEMY_NAME: BASIC_SHOOTER_LIMIT,
	SHOTGUNNER_ENEMY_NAME: SHOTGUNNER_LIMIT,
	DEFLECTOR_BOSS_ENEMY_NAME: DEFLECTOR_BOSS_LIMIT
}

const DEFLECTOR_BOSS_HEALTH = 1000
const DEFLECTOR_BOSS_DAMAGE = 10
const DEFLECTOR_BOSS_SPEED = 100
const DEFLECTOR_BOSS_PROJECTILE_SPEED = 300
const DEFLECTOR_BOSS_FIRERATE_COOLDOWN = 1.5
const DEFLECTOR_BOSS_SHOT_COUNT = 5
const DEFLECTOR_BOSS_BULLET_SCALE = 0.85
const DEFLECTOR_BOSS_DISTANCE_THRESHOLD = 700
const DEFLECTOR_BOSS_ENEMY_NAME = "The Deflector"
const DEFLECTOR_BOSS_GOLD_DROP_RANGE = 150
const DEFLECTOR_BOSS_XP_DROP_RANGE = 300
const DEFLECTOR_BOSS_XP_TYPE = 2
const DEFLECTOR_BOSS_GOLD_DROP_CHANCE = 1
const DEFLECTOR_BOSS_GOLD_DROP_COUNT = 50
const DEFLECTOR_BOSS_XP_DROP_COUNT = 50
const DEFLECTOR_BOSS_ITEM_DROP_CHANCE = 1
const DEFLECTOR_BOSS_ITEM_DROP_COUNT = 1
const DEFLECTOR_BOSS_MIN_SPAWN_DIST = 250
const DEFLECTOR_BOSS_SPAWN_RADIUS = 500
const DEFLECTOR_BOSS_LIMIT = -1
