extends Node

const BASIC_SHOOTER_HEALTH = 30
const BASIC_SHOOTER_DAMAGE = 10
const BASIC_SHOOTER_SPEED = 100
const BASIC_SHOOTER_PROJECTILE_SPEED = 300
const BASIC_SHOOTER_FIRERATE_COOLDOWN = 1.5
const BASIC_SHOOTER_MIN_DISTANCE_THRESHOLD = 200
const BASIC_SHOOTER_MAX_DISTANCE_THRESHOLD = 500
const BASIC_SHOOTER_ENEMY_NAME = "Basic Shooter"
const BASIC_SHOOTER_GOLD_DROP_RANGE = 15
const BASIC_SHOOTER_XP_DROP_RANGE = 50
const BASIC_SHOOTER_GOLD_DROP_COUNT = 1
const BASIC_SHOOTER_XP_DROP_COUNT = 5

const SNIPER_HEALTH = 50
const SNIPER_DAMAGE = 25
const SNIPER_SPEED = 150
const SNIPER_PROJECTILE_SPEED = 800
const SNIPER_FIRERATE_COOLDOWN = 3
const SNIPER_ENEMY_NAME = "Sniper"
const SNIPER_MIN_DISTANCE_THRESHOLD = 500
const SNIPER_MAX_DISTANCE_THRESHOLD = 800
const SNIPER_GOLD_DROP_RANGE = 30
const SNIPER_XP_DROP_RANGE = 50
const SNIPER_GOLD_DROP_COUNT = 3
const SNIPER_XP_DROP_COUNT = 8

const WEAK_RUSHER_HEALTH = 10
const WEAK_RUSHER_DAMAGE = 5
const WEAK_RUSHER_MIN_SPEED = 225
const WEAK_RUSHER_MAX_SPEED = 275
const WEAK_RUSHER_ENEMY_NAME = "Weak Rusher"
const WEAK_RUSHER_GOLD_DROP_RANGE = 25
const WEAK_RUSHER_XP_DROP_RANGE = 25
const WEAK_RUSHER_GOLD_DROP_COUNT = 0
const WEAK_RUSHER_XP_DROP_COUNT = 2

const TANKY_ENEMY_NAME = "Tanky"
const TANKY_SPEED = 50
const TANKY_DAMAGE = 15
const TANKY_HEALTH = 125
const TANKY_GOLD_DROP_RANGE = 30
const TANKY_XP_DROP_RANGE = 50
const TANKY_GOLD_DROP_COUNT = 3
const TANKY_XP_DROP_COUNT = 8

const SNIPER_LIMIT: int = 5
const TANKY_LIMIT: int = 8
const BASIC_SHOOTER_LIMIT: int = 15

const ENEMY_LIMITS = {
	TANKY_ENEMY_NAME: TANKY_LIMIT,
	SNIPER_ENEMY_NAME: SNIPER_LIMIT,
	BASIC_SHOOTER_ENEMY_NAME: BASIC_SHOOTER_LIMIT
}
