extends Node

const DEFAULT_STAGE: int = 1
const DEFAULT_CLEAR_CONDITION: int = 25
const DEFAULT_BOSS_STAGE_INCREMENT: int = 4
const DEFAULT_DOOR_POSITION: Vector2 = Vector2.ZERO
const DEFAULT_PLAYER_POSITION: Vector2 = Vector2.ZERO
const DEFAULT_ENEMIES_KILLED_THIS_STAGE: int = 0
const DEFAULT_ENEMIES_SPAWNING: int = 1
const DEFAULT_LEVEL_CLEARED: bool = false
