extends Node

const DEFAULT_PLAYER_SPEED: int = 300
const DEFAULT_FIRERATE: float = 0.5
const DEFAULT_DAMAGE: int = 10
const DEFAULT_PROJECTILE_SPEED: int = 1250
const STARTING_PLAYER_HEALTH: float = 100
const BASE_XP: int = 100
const LEVEL_MULTIPLIER: float = 1.15
const DEFAULT_LEVEL_UP_CONDITION: int = 100
const DEFAULT_KNOCKBACK: float = 100
